### ISSUE TITLE
non_field_errors Modul 5 

### ISSUE THREAD

**Issue by JonaspythonG** [bobby-didcoding/drf_course#15]
Hallo,

I have been working on a project directly on my webserver. Up until now, everything has been functioning well. However, when I attempt to create an admin user, I encounter Error 1.

I tried to create the same user again and realized that the user creation was successful because the console indicated that the user already exists. But when I try to retrieve the token using HTTPie, I face Error 2.

Does anybody know what could be done to resolve this?

ERROR1:
(venv) [11:59:43][root@xxx:/var/www/django/drf_course/backend]$ python manage.py createsuperuser
Username (leave blank to use 'root'): xxxxx
Email address: 
Password:
Password (again):
Traceback (most recent call last):
  File "/var/www/django/drf_course/backend/manage.py", line 22, in <module>
    main()
  File "/var/www/django/drf_course/backend/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
    return super().execute(*args, **options)
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 233, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 172, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/contrib/auth/models.py", line 155, in _create_user
    user.save(using=self._db)
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save
    self.save_base(
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/db/models/base.py", line 878, in save_base
    post_save.send(
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/var/www/django/drf_course/venv/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/var/www/django/drf_course/backend/ecommerce/signals.py", line 9, in report_uploaded
    Token.objects.create(user=instance)

ERROR 2:
(venv) [12:17:18][root@xxx:/var/www/django/drf_course/backend]$ http post http://localhostipadress/api-token-auth/ username=**xxx** password=**xxx**
HTTP/1.1 400 Bad Request
Allow: POST, OPTIONS
Content-Length: 68
Content-Type: application/json
Cross-Origin-Opener-Policy: same-origin
Date: Wed, 15 Nov 2023 12:52:38 GMT
Referrer-Policy: same-origin
Server: WSGIServer/0.2 CPython/3.9.2
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "non_field_errors": [
        "Unable to log in with provided credentials."
    ]
}

**Comment by JonaspythonG** [comment]
Errors have been fixed. I forgot to add 'rest_framework.authtoken' to the INSTALLED_APPS.
